In [8]:
import pandas as pd
import numpy as np
import seaborn as sns

In [29]:
df = pd.read_csv('../data/raw/Sample - Superstore.csv', encoding="latin-1")
print('Shape: ', df.shape)
df.head(20)

Shape:  (10064, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
5765,5766,US-2014-126340,11/8/2014,11/14/2014,Standard Class,EB-13870,Emily Burns,Consumer,United States,Redding,...,96003.0.0,West,TEC-PH-10004447,Technology,Phones,Toshiba IPT2010-SD IPÂ Telephone,333.576,3.0,0.2,25.0182

In [19]:
#Shipe Mode Valeur manquante d'apres le customer name manquant
df[df['Customer Name'].isna()]['Ship Mode'].isna().value_counts()

Ship Mode
False    345
True       6
Name: count, dtype: int64

In [26]:
#Sales Valeur manquante d'apres le customer name manquant
df[df['Customer Name'].isna()]['Sales'].isna().sum()

AttributeError: 'numpy.int64' object has no attribute 'value_counts'

In [21]:
#Ship Date Valeur manquante d'apres le customer name manquant
df[df['Customer Name'].isna()]['Ship Date'].isna().value_counts()

Ship Date
False    347
True       4
Name: count, dtype: int64

In [22]:
#Postal code Valeur manquante d'apres le customer name manquant
df[df['Customer Name'].isna()]['Postal Code'].isna().value_counts()

Postal Code
False    346
True       5
Name: count, dtype: int64

In [27]:
df.isna().corr()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Row ID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Order ID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Order Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ship Date,NaN,NaN,NaN,1.000000,-0.005974,NaN,0.002594,NaN,NaN,NaN,...,0.007092,NaN,NaN,NaN,NaN,NaN,0.007003,0.000021,NaN,NaN
Ship Mode,NaN,NaN,NaN,-0.005974,1.000000,NaN,-0.014301,NaN,NaN,NaN,...,0.012616,NaN,NaN,NaN,NaN,NaN,-0.016727,0.012772,NaN,NaN
Customer ID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer Name,NaN,NaN,NaN,0.002594,-0.014301,NaN,1.000000,NaN,NaN,NaN,...,-0.007666,NaN,NaN,NaN,NaN,NaN,-0.000040,-0.011439,NaN,NaN
Segment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Postal Code,NaN,NaN,NaN,0.007092,0.012616,NaN,-0.007666,NaN,NaN,NaN,...,1.000000,NaN,NaN,NaN,NaN,NaN,-0.010150,-0.015110,NaN,NaN
Region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product ID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sub-Category,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sales,NaN,NaN,NaN,0.007003,-0.016727,NaN,-0.000040,NaN,NaN,NaN,...,-0.010150,NaN,NaN,NaN,NaN,NaN,1.000000,0.000130,NaN,NaN
Quantity,NaN,NaN,NaN,0.000021,0.012772,NaN,-0.011439,NaN,NaN,NaN,...,-0.015110,NaN,NaN,NaN,NaN,NaN,0.000130,1.000000,NaN,NaN
Discount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Profit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10059,1281,CA-2016-160815,9/5/2016,9/6/2016,First Class,TR-21325,TOBY RITTER,Consumer,United States,Cedar Rapids,...,52402.0,Central,TEC-PH-10003505,Technology,Phones,Geemarc AmpliPOWER60,278.4000,3.0,0.00,80.7360
10060,7699,CA-2017-151799,12/14/2017,12/18/2017,Standard Class,BF-11170,BEN FERRER,Home Office,United States,Lawrence,...,1841.0,East,OFF-ST-10002790,Office Supplies,Storage,Safco Industrial Shelving,73.8500,1.0,0.00,2.2155
10061,8597,CA-2014-111934,5/5/2014,5/7/2014,First Class,GD-14590,GIULIETTA DORTCH,Corporate,United States,Arlington,...,22204.0,South,OFF-PA-10000474,Office Supplies,Paper,Easy-staple paper,35.4400,1.0,0.00,16.6568
10062,4962,CA-2014-156587,3/7/2014,3/8/2014,First Class,AB-10015,NaN,Consumer,United States,Seattle,...,98103.0,West,FUR-CH-10004477,Furniture,Chairs,"Global Push Button Manager's Chair, Indigo",48.7120,1.0,0.20,5.4801
10063,3998,CA-2015-105627,3/8/2015,3/12/2015,Standard Class,DK-12895,DANA KAYDOS,Consumer,United States,Kenosha,...,53142.0,Central,OFF-AR-10002704,Office Supplies,Art,Boston 1900 Electric Pencil Sharpener,14.9800,1.0,0.00,4.4940

In [51]:
def pseudonymize_row(row, salt_key):
    # Concaténation de la valeur et du sel
    data = f"{row}{salt_key}".encode('utf-8')
    # Calcul du HMAC-SHA256
    hashed = hmac.new(salt_key.encode('utf-8'), data, hashlib.sha256).hexdigest()
    return hashed

# Application au DataFrame
df['pseudonymized_id'] = df['Customer Name'].apply(lambda x: pseudonymize_row(x, 'SECRET_SALT_KEY'))
df['pseudonymized_id']

0        21b5b7c44749bfa1495eed34c4779134ff31494e1957cd...
1        21b5b7c44749bfa1495eed34c4779134ff31494e1957cd...
2        7ffcc35fb1e9df2315b2b1a75c146697860a79627e08e5...
3        140e9ee473e56c04db7eb0f13a818af4d9a1a63161e3ed...
4        140e9ee473e56c04db7eb0f13a818af4d9a1a63161e3ed...
                               ...
10059    fc09c44bf1b987867a27f3c1330bb27f291e4313aadd6a...
10060    39de06295c0eb9a3611c833c702b8232cc7847a193ee31...
10061    f268a86cc4e781c45398e7a2e7404c7e3d0c27202373c6...
10062    65ac08f7b52e77dc6b89d878d39717132bdb77137e2661...
10063    178e641a2efdc78169fab507404b6e3d23f927fa663b9b...
Name: pseudonymized_id, Length: 10064, dtype: object