In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
df = pd.read_csv('../data/raw/Sample - Superstore.csv')
df.shape

(10064, 21)

In [4]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [5]:
df.dtypes
# il ya juste un int, des object, et float, pour les dates et les str

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code       object
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity         float64
Discount         float64
Profit           float64
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10064 entries, 0 to 10063
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10064 non-null  int64
 1   Order ID       10064 non-null  object
 2   Order Date     10064 non-null  object
 3   Ship Date      9963 non-null   object
 4   Ship Mode      9763 non-null   object
 5   Customer ID    10064 non-null  object
 6   Customer Name  9713 non-null   object
 7   Segment        10064 non-null  object
 8   Country        10064 non-null  object
 9   City           10064 non-null  object
 10  State          10064 non-null  object
 11  Postal Code    9864 non-null   object
 12  Region         10064 non-null  object
 13  Product ID     10064 non-null  object
 14  Category       10064 non-null  object
 15  Sub-Category   10064 non-null  object
 16  Product Name   10064 non-null  object
 17  Sales          9863 non-null   float64
 18  Quantity       9865 non-null   float64
 19  Discount       10064 non-null  float64
 20  Profit         10064 non-null  float64
dtypes: float64(4), int64(1), object(16)
memory usage: 1.6+ MB

In [7]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164

In [8]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
10059,1281,CA-2016-160815,9/5/2016,9/6/2016,First Class,TR-21325,TOBY RITTER,Consumer,United States,Cedar Rapids,...,52402.0,Central,TEC-PH-10003505,Technology,Phones,Geemarc AmpliPOWER60,278.400,3.0,0.0,80.7360
10060,7699,CA-2017-151799,12/14/2017,12/18/2017,Standard Class,BF-11170,BEN FERRER,Home Office,United States,Lawrence,...,1841.0,East,OFF-ST-10002790,Office Supplies,Storage,Safco Industrial Shelving,73.850,1.0,0.0,2.2155
10061,8597,CA-2014-111934,5/5/2014,5/7/2014,First Class,GD-14590,GIULIETTA DORTCH,Corporate,United States,Arlington,...,22204.0,South,OFF-PA-10000474,Office Supplies,Paper,Easy-staple paper,35.440,1.0,0.0,16.6568
10062,4962,CA-2014-156587,3/7/2014,3/8/2014,First Class,AB-10015,NaN,Consumer,United States,Seattle,...,98103.0,West,FUR-CH-10004477,Furniture,Chairs,"Global Push Button Manager's Chair, Indigo",48.712,1.0,0.2,5.4801
10063,3998,CA-2015-105627,3/8/2015,3/12/2015,Standard Class,DK-12895,DANA KAYDOS,Consumer,United States,Kenosha,...,53142.0,Central,OFF-AR-10002704,Office Supplies,Art,Boston 1900 Electric Pencil Sharpener,14.980,1.0,0.0,4.4940

In [9]:
df.describe(include='all')
#il y a du manque de valeurs pour sales et quatites

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
count,10064.000000,10064,10064,9963,9763,10064,9713,10064,10064,10064,...,9864,10064,10064,10064,10064,10064,9.863000e+03,9865.000000,10064.000000,10064.000000
unique,NaN,5009,1495,1334,4,793,810,6,1,633,...,705,4,1862,6,17,1850,NaN,NaN,NaN,NaN
top,NaN,CA-2017-100111,9/5/2016,12/16/2015,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,...,10035.0,West,OFF-PA-10001970,Office Supplies,Binders,Easy-staple paper,NaN,NaN,NaN,NaN
freq,NaN,14,39,35,5822,38,36,5163,10064,896,...,259,3224,19,5942,1532,48,NaN,NaN,NaN,NaN
mean,4994.397059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.950322e+03,3.780233,0.157501,28.571309
std,2885.848580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.410673e+04,2.240134,0.210586,233.509461
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.440000e-01,-5.000000,0.000000,-6599.978000
25%,2496.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.729000e+01,2.000000,0.000000,1.724800
50%,4989.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.450000e+01,3.000000,0.200000,8.643600
75%,7494.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.107600e+02,5.000000,0.200000,29.331600
max,9994.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.131924e+06,14.000000,1.500000,8399.976000

In [10]:
df['Row ID'].isna().value_counts()
df['Order ID'].isna().value_counts()
df['Order Date'].isna().value_counts()
df['Ship Date'].isna().value_counts() #101
df['Ship Mode'].isna().value_counts() #301
df['Customer ID'].isna().value_counts() 
df['Customer Name'].isna().value_counts() #351
df['Segment'].isna().value_counts() 
df['Country'].isna().value_counts() 
df['City'].isna().value_counts() 
df['State'].isna().value_counts() 
df['Postal Code'].isna().value_counts() #200
df['Region'].isna().value_counts() 
df['Product ID'].isna().value_counts() 
df['Category'].isna().value_counts() 
df['Sub-Category'].isna().value_counts()
df['Product Name'].isna().value_counts()
df['Sales'].isna().value_counts() #201
df['Quantity'].isna().value_counts() #199
df['Discount'].isna().value_counts() 
df['Profit'].isna().value_counts()

Profit
False    10064
Name: count, dtype: int64

In [11]:
df.duplicated().value_counts()
#34 duplicated row

False    10030
True        34
Name: count, dtype: int64

In [12]:
df['Row ID'].dtypes
df['Order ID'].dtypes
df['Order Date'].dtypes
df['Ship Date'].dtypes #101
df['Ship Mode'].dtypes #301
df['Customer ID'].dtypes 
df['Customer Name'].dtypes #351
df['Segment'].dtypes 
df['Country'].dtypes 
df['City'].dtypes 
df['State'].dtypes 
df['Postal Code'].dtypes #200
df['Region'].dtypes 
df['Product ID'].dtypes 
df['Category'].dtypes 
df['Sub-Category'].dtypes
df['Product Name'].dtypes
df['Sales'].dtypes #201
df['Quantity'].dtypes #199
df['Discount'].dtypes 
df['Profit'].dtypes

dtype('float64')

In [13]:
pattern = r'^\d{2}/\d{2}/\d{4}$'
r = df['Ship Date'].str.match(pattern, na=False).value_counts()
r

Ship Date
False    7501
True     2563
Name: count, dtype: int64

In [14]:
df.nunique()
#le nombre d'elements unique pour choisir le bonne type d'necodage (categorielle)

Row ID           9994
Order ID         5009
Order Date       1495
Ship Date        1334
Ship Mode           4
Customer ID       793
Customer Name     810
Segment             6
Country             1
City              633
State              86
Postal Code       705
Region              4
Product ID       1862
Category            6
Sub-Category       17
Product Name     1850
Sales            5738
Quantity           15
Discount           13
Profit           7287
dtype: int64

In [15]:
df.isnull().sum()

Row ID             0
Order ID           0
Order Date         0
Ship Date        101
Ship Mode        301
Customer ID        0
Customer Name    351
Segment            0
Country            0
City               0
State              0
Postal Code      200
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales            201
Quantity         199
Discount           0
Profit             0
dtype: int64

In [16]:
%pip install setuptools

print("done")
#profil = ProfileReport(df, titre="Rapport de profilage")
#profile.to_notebook_iframe() # Pour les notebooks Jupyter
#profile.to_file("rapport.html")

/home/noha/DEVAI/DataStore360/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.
done

In [17]:
from ydata_profiling import ProfileReport
print('ok')

ok

/tmp/ipykernel_91301/1485448827.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [18]:
profile = ProfileReport(
    df,
    title="DataStore360 - Data Profiling Report",
    explorative=True
)

profile.to_file("../reports/rapport_profiling.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|███████████████████████████████████| 21/21 [00:00<00:00, 17109.63it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [53]:
#Duplicated Rows:
# I drop 34 duplicated rows je decide de les droper en utilisants drop_duplicates()
df.duplicated()
#df.shape

0        False
1        False
2        False
3        False
4        False
         ...
10059    False
10060    False
10061    False
10062    False
10063    False
Length: 10030, dtype: bool

In [108]:
#Missiong value :
df.isna().sum().sort_values(ascending=False)

missing = pd.DataFrame({
    "missing_count" : df.isna().sum(),
    "missing_pencent" : df.isna().mean() *100
})
missing = missing[missing['missing_count'] > 0]
missing.sort_values('missing_count', ascending=False)

               missing_count  missing_pencent
Customer Name            317         3.160518
Ship Mode                301         3.000997
Sales                    200         1.994018
Postal Code              199         1.984048
Quantity                 199         1.984048
Ship Date                101         1.006979

In [160]:

# Customer Name
df.loc[df["Customer Name"].isna(), 'Customer ID'] #246
customer_check = (
    df.groupby('Customer ID')['Customer Name'].agg(['count', 'first'])
)
customer_check.head(10)
customer_check["first"].isna().sum()
#j'ai regrouper les lignes par Customer Id , puis j'ai pris le premier Customer Name trouve pour chaque Client, et compter combien de Customer ID differnts ont un Customer Name manquat j'ai trouver 1
customer_check[customer_check['first'].isna()] # LD-16855	0	None
#Il ua un client Customer Id pour lequel aucun non n'est disponible dans les donnees
customer_idmissing = customer_check[customer_check['first'].isna()].index
df[df["Customer ID"].isin(customer_idmissing)][
    ["Order ID", "Customer ID", "Customer Name"]
]
#df.loc[df['Customer ID'].isin(customer_idmissing)] # CA-2016-152331	
#df.loc[df['Customer ID'] =='LD-16855', ['Order ID', 'Customer Name']]
#r = df.groupby('Order ID')[['Customer Name', 'Customer ID']].agg(['count', 'first'])
#r.loc[r['Order ID'] == "CA-2016-152331"]
# => Aucun CUstomer Name disponible et ce Customer ID a un

            Order ID Customer ID Customer Name
6505  CA-2016-152331    LD-16855           NaN

In [77]:
df['Segment'].value_counts()
#tester les fautes d'orthographes
df['Postal Code'].value_counts()

Postal Code
10035.0      259
10009.0      227
10024.0      223
94122.0      194
10011.0      188
            ...
34741.0        1
94109.0.0      1
30080.0.0      1
6810.0         1
72762.0        1
Name: count, Length: 705, dtype: int64

In [88]:
OrderDate = pd.to_datetime(df['Order Date'], errors='coerce')
ShapeDate = pd.to_datetime(df['Ship Date'], errors='coerce')
OrderDate.isna().value_counts()
# lors du casting de type de Order Date il aura des dates invalides(envirant de 301) apres le casting
#Pour le Ship Date il ya 101 nan avant et apres le casting

Order Date
False    9729
True      301
Name: count, dtype: int64

In [101]:
r = df['Customer Name'].str.replace(r'\s+', '', regex=True).str.lower()
r.isna().value_counts()

Customer Name
False    9713
True      317
Name: count, dtype: int64

Customer Name    317
Ship Mode        301
Sales            200
Postal Code      199
Quantity         199
Ship Date        101
Order ID           0
Row ID             0
Order Date         0
Country            0
City               0
Segment            0
Customer ID        0
Region             0
State              0
Product ID         0
Category           0
Product Name       0
Sub-Category       0
Discount           0
Profit             0
dtype: int64